### ISSUE TITLE
[01분반] 4주차 이론강의에서 한 함수 안에 여러번의 같은 이름의 변수가 생길 때, 어떤 식으로 작동하는지에 대한 질문입니다.

### ISSUE THREAD

**Issue by sleepisparrow** [PLASLaboratory/ComputerProgramming3_CNU_2023#11]
## 분반
e.g. 01

## OS
e.g.  Windows 10 (WSL)

## Describe the Bug
만약에 fun이라는 함수가 있다고 가정하고, 함수가 이렇게 생겼다고 하면: 
```c
void fun () {
    int i = 0;
    if (i == 0) {
        int i = 1;
        if (i == 1) {
            int i = 2;
        }
    }
}
```
이 함수의 스택 프레임에는 여러개의 i 들이 저장될 수 있는 공간이 따로 생기는 것인가요? 아니면 어떤 식으로 스택 프레임이 생성되는 건가요?

**Comment by CNUCOM** [comment]
네, 좋은 질문입니다.

각 `i`는 우선 자신을 둘러싸고 있는 중괄호 (`{`, `}`) 로 묶여있는 block 내에서만 보이고, 해당 block을 빠져나가면 사라집니다. 마치 함수의 지역변수와 비슷합니다.

이러한 `i` 는 함수의 새로운 지역변수가 아니므로 원칙적으로는 새로 스택프레임을 push 하지는 않습니다.

여러가지 방법으로 메모리에 위치시킬 수 있는데, 그 중에서 이 변수 `i`만을 위한 미니? 스택프레임을 만들어서 push-pop을 하는 것이 제일 간단한 방법입니다. 결국 새 block을 새 함수처럼 취급하는 방법이라고도 볼 수 있지만,
스택프레임 내에 인자, 리턴주소가 없어도 되므로 상당히 간단해집니다.

더 궁금한 것은 3학년 컴파일러개론 수업에서...
