### ISSUE TITLE
각종 질문, 중간고사 전날부터는 받지 않습니다.

### ISSUE THREAD

**Issue by Masterwhiece** [PLASLaboratory/ComputerProgramming3_CNU_2023#21]
시험 공부 도중 질문 많이 하게 되실텐데요.
중간고사 전날부터는 받지 않습니다. 참고 바랍니다.
4월 22일 토요일 23시 59분까지 받겠습니다.

**Comment by CNUCOM** [comment]
지필고사 (종이에 보는 시험)이고 
정리 자료들은 시험범위에 들어가지 않는 것도 참고하시기 바랍니다.
1장도 시험범위에 안들어갑니다.
