### ISSUE TITLE
[00분반] 시험 범위에 관하여 질문드립니다.

### ISSUE THREAD

**Issue by aabccde** [PLASLaboratory/ComputerProgramming3_CNU_2023#22]
## 분반
00분반

## 질문 내용
사이버 캠퍼스의 공지사항에 강의 영상 이외의 내용은 시험에 나오지 않는다고 하셨는데, 그러면 1-1 C 프로그래밍 개요 부분도 시험에 나오지 않나요?

**Comment by CNUCOM** [comment]
1장은 시험범위에 안 들어갑니다

**Comment by aabccde** [comment]
답변 감사합니다!
