### ISSUE TITLE
[00분반] 9주차 수업에 관하여,

### ISSUE THREAD

**Issue by seunghyeoks** [PLASLaboratory/ComputerProgramming3_CNU_2023#23]
## 분반
00분반

## 질문
9주차 수업일정에 관해서 질문드립니다!

00분반기준 
월요일 오전 11시 수업은 미실시 및 오후 7시에 시험진행
목요일 오후 4시 수업은 영상강의로 대체
가 맞나요?? 이럴경우 실제로 9주차는 시험때만 등교하면 될까요??

**Comment by CNUCOM** [comment]
네 정리하면 00반 01반 모두
* 다음주는 월요일 저녁(7시40분에 중간고사)에 오시고, 추가 등교 할 일은 없습니다.
단, 평소와 같이 동영상강의를 그 다음주 월요일(5월1일)까지 반드시 수강하셔야 사이버캠퍼스 출석이 인정됩니다.

* 그 다음주 월요일 대면 수업은 근로자의 날로 휴강입니다.
즉, 중간고사 후에 처음으로 하는 대면 수업은 5월4일 실습 시간입니다.
