### ISSUE TITLE
[01분반] 9주차 강의가 아직 안 올라온 것이 맞나요?

### ISSUE THREAD

**Issue by yerimmii** [PLASLaboratory/ComputerProgramming3_CNU_2023#27]
공지에 '지난번 올린 동영상'이 혹시 9주차 영상이 맞을까요?
강의 학습기간이 4/17~5/3인데 아무것도 올라오지 않아서 질문드립니다.

**Comment by CNUCOM** [comment]
01분반은 9주차 강의자료 게시에 문제가 있어서 이제 공개되었습니다. (4월30일 22시40현재)
정말 미안합니다.
4일까지로 수강기한 연장했으니 참고하시기 바랍니다.

질문 감사합니다.
관련해서 추가로 궁금한 것은 깃헙이나 메일로 주시기 부탁합니다.
