### ISSUE TITLE
[중요][01분반 필독!] 9주차 강의자료가 늦게 공개되었습니다! (아래 글에 대한 답변)

### ISSUE THREAD

**Issue by CNUCOM** [PLASLaboratory/ComputerProgramming3_CNU_2023#28]
01분반은 9주차 강의자료 게시에 문제가 있어서 이제 공개되었습니다. (4월30일 22시40현재)
정말 미안합니다.
4일까지로 기한 연장했으니 참고하시기 바랍니다.

관련해서 추가로 궁금한 것은 깃헙이나 메일로 주시기 부탁합니다.

**Comment by 202002530-LeeWoojin** [comment]
저는 컴퓨터프로그래밍3 9주 3회차 자료가 올라와있지 않는 상태인데, 계속 미완료 상태로 떠서 출석이 되지 않은채 '학습 중'이라고 뜹니다. 어떻게 처리해야하는건가요?

**Comment by Masterwhiece** [comment]
@202002530-LeeWoojin
다시 한 번 확인해보시겠어요?

**Comment by 202002530-LeeWoojin** [comment]
현재 사이버캠퍼스에 다시 로그인하고 확인해보니 자료들이 정상적으로 올라온 상태입니다! 확인해주셔서 감사합니다!
