### ISSUE TITLE
[01분반] 텀프로젝트에서 문자열을 입력받을때 공백도 포함한 문자열 도 입력받아야되나요?

### ISSUE THREAD

**Issue by seunghyeoks** [PLASLaboratory/ComputerProgramming3_CNU_2023#44]
## 분반
01

## OS
macOS 

## Describe 
가산점 부여 항목 확인중에 궁금한 점이 생겨 질문드립니다. command line으로 문자열을 입력 받을때 공백이 들어있는 문자열이 입력될 수 있나요??

**Comment by jhc365** [comment]
그 경우는 고려하지 않으셔도 됩니다.
