### ISSUE TITLE
탐색기의 위치가 올바르지 않게 연동되었는데 원래 위치로 어떻게 옮기나요? 

### ISSUE THREAD

**Issue by yeonicy** [PLASLaboratory/ComputerProgramming3_CNU_2023#6]
vscode 에서 사이드바에 뜨는 탐색기에서 연동된 위치는 root로 뜨는데 연동된 위치를 home-사용자 로 변경하고 싶습니다. 어떻게 해야 할까요?

**Comment by jhc365** [comment]
wsl 상에서 cd 명령어로 해당 경로로 이동 후 code . 명령어를 실행할 경우 해당 폴더에 VS Code가 실행되게 됩니다.
