### ISSUE TITLE
[01분반] 1주차 실습 관련해 질문 드립니다!

### ISSUE THREAD

**Issue by hsjni0110** [PLASLaboratory/ComputerProgramming3_CNU_2023#8]
과제 설명 란에서는 실행 파일 및 보고서를 zip파일로 압축해서 제출하라고 이해했습니다.

단, 실행 파일 양식이 .c 확장자로 된 파일을 보내는 것인지

아니면 빌드된 파일을 보내는 것인지 여쭤보고자 합니다.

늘 고생하십니다. 감사합니다:)

**Comment by HyeonCheol1211** [comment]
저도 궁금합니다!

**Comment by Masterwhiece** [comment]
.c 파일은 C 코드 파일입니다.
실행파일은 gcc로 컴파일해 만들어진, 말그대로 '실행되는' 파일을 제출하시면 됩니다.
